on:
  push:
    branches:
      - main  # Trigger workflow on push to main
  pull_request:
    branches:
      - main  # Trigger workflow for pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest  # Choose the OS for the build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout code from GitHub repository

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Define the PHP version (adjust as needed)

    - name: Install dependencies
      run: |
        composer install --no-progress --no-suggest --prefer-dist  # Install PHP dependencies

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Run tests
      run: ./vendor/bin/phpstan analyse  # Run PHP Stan

    - name: Build and Deploy
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to Production..."
        # Add your deployment script here (e.g., SSH deployment)
